// frontend/src/components/ui/WorkspacePage.vue
<template>
  <section class="ui-workspace-page">
    <PageStateHeader
      :title="title"
      :description="description"
      :chips="chips"
      :compact="compact"
    >
      <template
        v-if="$slots.meta"
        #meta
      >
        <slot name="meta" />
      </template>
      <template
        v-if="$slots.actions"
        #actions
      >
        <slot name="actions" />
      </template>
      <template
        v-if="$slots.below"
        #below
      >
        <slot name="below" />
      </template>
    </PageStateHeader>

    <MetricStrip
      v-if="metrics.length"
      :items="metrics"
    />

    <div
      class="ui-workspace-page__body"
      :class="{ 'ui-workspace-page__body--split': Boolean($slots.side) }"
    >
      <main class="ui-workspace-page__main">
        <slot />
      </main>
      <aside
        v-if="$slots.side"
        class="ui-workspace-page__side"
      >
        <slot name="side" />
      </aside>
    </div>
  </section>
</template>

<script setup lang="ts">
import MetricStrip from './MetricStrip.vue'
import PageStateHeader from './PageStateHeader.vue'

type MetricStripItem = {
  label: string
  value: string | number
  hint?: string
  tone?: 'accent' | 'success' | 'warning' | 'danger'
}

type PageStateChip = {
  label: string
  tone?: 'neutral' | 'accent' | 'success' | 'warning' | 'danger' | 'muted'
}

withDefaults(defineProps<{
  title: string
  description?: string
  chips?: PageStateChip[]
  metrics?: MetricStripItem[]
  compact?: boolean
}>(), {
  description: '',
  chips: () => [],
  metrics: () => [],
  compact: false
})
</script>

// frontend/src/components/layout/WorkspacePage.tsx
import type { ReactNode } from 'react'
import { Space, Tag } from 'antd'

export interface MetricItem {
  label: string
  value: string | number
  hint?: string
  tone?: 'accent' | 'success' | 'warning' | 'danger'
}

interface WorkspacePageProps {
  title: string
  description?: string
  chips?: Array<{ label: string; color?: string }>
  metrics?: MetricItem[]
  actions?: ReactNode
  side?: ReactNode
  children: ReactNode
}

export function MetricStrip({ items }: { items: MetricItem[] }) {
  if (!items.length) return null
  return (
    <div className="metric-strip">
      {items.map((item) => <div className="metric-card" key={item.label}><div className="label">{item.label}</div><div className="value">{item.value}</div>{item.hint && <div className="muted-text" style={{ marginTop: 8, fontSize: 12 }}>{item.hint}</div>}</div>)}
    </div>
  )
}

export function WorkspacePage({ title, description, chips = [], metrics = [], actions, side, children }: WorkspacePageProps) {
  return (
    <section className="workspace-page">
      <header className="workspace-header">
        <div>
          <Space size={6} wrap>{chips.map((chip) => <Tag key={chip.label} color={chip.color}>{chip.label}</Tag>)}</Space>
          <h1 className="workspace-title">{title}</h1>
          {description && <p className="workspace-description">{description}</p>}
        </div>
        {actions && <div>{actions}</div>}
      </header>
      <MetricStrip items={metrics} />
      <div className={side ? 'workspace-grid two' : 'workspace-grid'}>
        <main>{children}</main>
        {side && <aside>{side}</aside>}
      </div>
    </section>
  )
}
